import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className="bg-gray-50 min-h-screen">
        <header className="w-full bg-white shadow p-4 mb-8">
          <div className="container mx-auto flex items-center justify-between">
            <h1 className="text-2xl font-bold text-blue-700">EdBridge Africa</h1>
            {/* TODO: Add language toggle and user menu here */}
          </div>
        </header>
        <main className="container mx-auto px-4">{children}</main>
      </body>
    </html>
  )
}
